# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle :compinstall filename '/home/s/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install

PROMPT="%B%F{red}%(?..%? )%f%b%B%F{green}%n%f%F{white}@%f%F{green}%m%f%b %F{magenta}%B%40<..<%~%<< %b%f%B$%b "
